orka-utils.c, orka-utils.h
This PR adds a function inside orca-utils.h to convert ISO-8601 timestamp to UNIX timestamp in milliseconds.
=> Add ISO-8601 to unix converter

orka-utils.c, orka-utils.h
Followed stensalweb's suggestions to improve "iso8601_to_unix_ms", that now is called "orka_iso8601_to_unix_ms".
=> Changed ISO-8601 to unix conversion to orka's json-scanf convention

bot-echo.cpp, bot-pin.cpp, bot-ping-pong.cpp
I removed unnecessary username verification because of two reasons:
1 - If the author is not the bot, it's also no the client, obviously.
2 - If an user had the same username of the bot, his messages would be ignored, because of the discriminator not being compared. But this could be easily solved by comparing IDs, so the most important reason is the first one.
=> Remove unnecessary username verification.

orka-utils.c
In this PR, I changed two things:
1 - A "size_t" variable was declared as "NULL", which is for pointers, so that caused compiling warnings.
2 - Inside orka_iso8601_to_unix_ms, it was casting "p" to "long long*" instead of "int64_t*".
=> Changed (long long*) casting to (int64_t*) casting inside orka_iso8601_to_unix_ms and changed size_t declaration from NULL to 0.

libdiscord.h
I had a problem when building the latest version on Windows, my compiler wasn't recognizing `uint64_t`, so I added `<stdint.h>` include header to `libdiscord.h`.
=> Add stdint.h include to libdiscord.h

orka-utils.c
Change `int` to `int64_t` inside `orka_iso8601_to_unix_ms`
=> Change int to int64_t inside orka_iso8601_to_unix_ms

json-printf.c
free temp memory allocated in json-printf.c
=> n1612666976

libdiscord.h
Changed `EMBED_MAX_FIELDS` from `25` to `25 + 1`, because of using of null-terminated list.
=> Changed EMBED_MAX_FIELDS from 25 to 25 + 1, because of using of null-terminated list.

json-scanf.c
skip the application of %F if the value is null, this is a quick fix but not an ideal fix
=> n1612832348

discord-public-channel.cpp, libdiscord.h
Add `init`, `cleanup` and `json_load` functions to `message::reference`
=> Add init, cleanup and json_load functions to message::reference

json-scanf.c, test/test-api.cpp, test/test-json-scanf-E.c, test/test-json-scanf-array.c, test/test-json-scanf.c
use ':' instead of '%' to differentiate the format strings that are used to extract json values
=> n1612916658

libdiscord.h
Add webhook name limit: I added the `Create Webhook` link as URL that specifies the limits because there's no `Webhook Limits` or something like that on discord documentations, but the name limit (80) is specified in the `Create Webhook` section.
And, it cannot contain "clyde" inside the string. Cannot either be "aclydef", or "Clyde", even if it's uppercase. This detection is something we should do when adding the feature to create the webhook.
=> Add webhook name limit

ntl.c, ntl.h
ntl_to_buf and ntl_to_abuf can return negative values for error so we have to keep them as int
=> n1613066012

json-actor.c, test/test-json-actor.c
move the advance of position to parse_apath_value so the test input is a well formed string, and this will also improve the clarity of the code
=> n1613073551

discord-common.h
Increased max prefix length from 5 to 32.
Reasons: let's suppose there's a bot called `Potato` and it's developer choosed to use `potato.` as prefix, lilke `potato.help`, `potato.clear` etc. It won't fit into 5 characters (or 4, because of the null-terminated one).
=> Increase prefix max length

discord-common.h, libdiscord.h
Add `default_message_notification_level` to `discord-common.h` and use `code` instead of `int`
=> Add default_message_notification_level to discord-common.h and use code instead of int

discord-public-channel.cpp, orka-utils.c, orka-utils.h
feat: add `orka_unix_ms_to_iso8601` and provide embed timestamp writing to `embed::to_json`
=> feat: add orka_unix_ms_to_iso8601 and provide embed timestamp writing to embed::to_json

libdiscord.h
fix: change `guild::dati::joined_at` from `int64_t `to `uint64_t`
=> fix: change guild::dati::joined_at from int64_t to uint64_t

json-actor.c, test/test-json-injector.c
feat: support `|F|`, no spaces is allowed, this will keep the C value to JSON string conversion without adding double quotes to enclose the result
=> n1613531110

json-actor.c, json-actor.h, test/test-json-injector.c
refactor: use the C convention v for va_list and a for allocation to name json_inject and json_extract`s variant.
=> n1613552751

discord-public-channel.cpp, orka-utils.c
fix: remove `@todo` and add timezone addition inside `orka_unix_ms_to_iso8601`, use `|F|` inside `embed::to_json`
Please, use `Merge Squash`.
=> fix: remove @todo and add timezone addition inside orka_unix_ms_to_iso8601, use |F| inside embed::to_json

discord-public.cpp
fix: settings cannot be a local variable as it will be returned from the fast_init.
=> n1613701793

discord-public.cpp
feat: add a check to make sure fast_init is called only once
=> n1613709500

discord-public-guild.cpp, discord-public-user.cpp, discord-websockets.cpp
fix: the regression caused by converting struct initializer to assignment which miss the fields that are not present.
=> n1613874589

common/json-actor.c, common/ntl.h
refactor: 1. use strncmp to improve code clarity; 2. fixes the ntl diagram
=> n1613951139

discord-public-channel.cpp
Remove unnecessary verifications, because only the `message_id` is need according with [discord documentation](https://discord.com/developers/docs/resources/channel#message-object-message-reference-structure)
=> fix: only the message_id is needed

common/json-actor.c
fix: if NULL pointers and @(will be renamed as @A) both exist, NULL pointer should be treated as not available
=> n1614014745

discord-common.h
fix: include `<stdint.h>` inside `discord-common.h`
I had a problem compiling the tests, because `uint64_t` wasn't detected.
=> fix: include <stdint.h> inside discord-common.h

discord-public-channel.cpp
fix: use `@A` and remove `0xFFFFFFFFFFFFFFFF` from `message::edit::run`
=> fix: use @A and remove 0xFFFFFFFFFFFFFFFF from message::edit::run

common/ntl.c, common/ntl.h
feat: add ntl_to_buf2 to support only extra parameter so it can be directly invoked in json_inject
=> n1614120279

common/json-struct.c
fix: the generated function types for callbacks
=> n1614352001

common/orka-utils.c
fix: orka_timestamp_ms is truncated in 32-bit
=> n1614378753

common/curl-websocket.h
fix: use header guard `#endif` at the end of the file
Please, use `Merge Squash`.
=> fix: use header guard #endif at the end of the file

.gitignore
fix: add `.vscode` to `.gitignore`
Note: this will solve a problem for VSC users, when they add a file called `c_cpp_properties.json` inside `.vscode` to add the include paths. If it's inside `.gitignore`, they can easily use `git add .` and `git pull`, without commiting this changes.
=> fix: add .vscode to .gitignore

.gitignore
fix: change `specs` to `specs-code` in `.gitignore`
=> fix: change specs to specs-code in .gitignore

bots/bot-questionnaire.cpp, common/json-actor-boxed.c, common/json-actor-boxed.h
feat: use NTL_T and uint64_t to avoid casting by callers
=> n1614886861

.gitignore
fix: add `.c` and `.h` files to `.gitignore`
Please use `Merge Squash`.
=> fix: add .c and .h files to .gitignore

bots/bot-fetch-messages.cpp, discord-public-channel.cpp, libdiscord.h
refactor: move message::get_list to gen_channel_messages so it maps to the get channel messages end point's url, this will make searching implemented endpoint easier
=> n1615945326

common/user-agent.h
It won't affect Ubuntu build, just fix problems with Windows build.
=> fix: add pthread.h include inside user-agent.h

docs/BUILDING_WITH_WINDOWS.md
fix: remove unnecessary Makefile code from Windows build tutorial
=> fix: remove unnecessary Makefile code from Windows build tutorial

.vscode/c_cpp_properties.json
fix: remove linux default folders, because Visual Studio Code automatically includes them.
=> fix: remove linux default folders, because vsc automatically includes

Makefile
Using `sort wildcard` has two advantages:
1. It's more portable because it doesn't need ls command.
2. Uses Makefile native language.
=> fix: use sort wildcard instead of shell ls

bots/bot-embed-formatting.c, discord-misc.c, discord.h
This PR allows for setting the title of an embed with additional formatting, e.g.:
`discord_embed_set_title(embed, "String: %s Integer: %d Scientific Notation: %E", "Test", 42, 12345678);`
=> Allow printf-esque formatting in embed-titles

README.md, common/js_user-agent.c, common/user-agent.c, common/user-agent.h, common/websockets.c, common/websockets.h, config.json, discord-adapter.c, discord-client.c, discord-gateway.c, discord-internal.h, discord-voice-connections.c, docs/BUILDING_A_BOT.md, examples/bot-elitebgs.c, github-adapter.c, github-client.c, github-internal.h, reddit-adapter.c, reddit-client.c, reddit-internal.h, slack-client.c, slack-internal.h, slack-socketmode.c, slack-webapi.c, test/test-cee.c, test/test-js-bindings.c
Closes #694. This PR introduces the ability of toggling particular logging sections (aka modules). If you wanted to disable `user-agent` and `websockets` logging it wouldn't be possible before because all logging would share the same global variable. This also means the user wouldn't be able to use any of the [log.c](https://github.com/rxi/log.c) functions without it interfering with Orca's internal logging. This PR makes it possible to start individual modules via `logconf_setup()`, and also to branch it to submodules by calling `logconf_branch()`, the latter ensures that the same file-descriptor (and some other resources) will be shared by the modules of the same family.
=> Modularized logging

docs/INTERNALS.md
Some sentences were moved into other sections. So it goes more like:
Prelog: Goals of the Guide. The prelog was reworded.
Introduction: Introducing Orca (the content was originally there) and how the guide will work
Just wording tweaks in Orca Specs and Examples, nothing big.
discord*.c, github*.c, reddit*.c, and slack*.c text simply identifies what they are
Choosing an endpoint only got some minor wording tweaks.
I dropped the questions reference to the bottom.
Some suggestions for future content would be:
- Try to refrain from using "I" to the best of your ability. Remember: there's always a different way of wording something! Using "you" should be fine as it fits the context of the guide.
- Prepositional phrases such as "Because of this," or "it may be useful if you are a regular user …
=> Proofread of Internals Guide

README.md, common/third-party/curl-websocket.c, common/user-agent.c, common/user-agent.h, discord-adapter.c, discord-gateway.c, discord-ratelimit.c, docs/BUILDING_A_BOT.md
- Replace clock() functions with time(), the first one is inaccurate. (44d2f8ef2fe7603bb1eb1162872f66bfcda39f2c)
- Fixes regression of not de-referencing a pointer. (44d2f8ef2fe7603bb1eb1162872f66bfcda39f2c)
- Takes elapsed milliseconds into consideration if using `Date` header to calculate ratelimiting cooldown. (c508d8cafa9eabcaded0d0138483e236a1f02c3d)
=> WebSockets synchronization and Discord ratelimiting
