cee-studio/orca

discord-public-message.cpp, docs/ROADMAP.md, libdiscord.h
In this PR, I add message::del function for deleting messages. I don't use message::delete because C++ generates a compile error because of "delete" being an operator.
=> Add message::del function.

ntl.h
=> n1612019672

.cee-repo.config
add the default repo config for automating commit and creating pull a request
=> n1612020169

github-v3-git-op.cpp, test-git2.cpp
1. use commit message as the pull message; 2. read from .cee-repo.config
=> n1612020726

discord-common.h, discord-public-channel.cpp, discord-public-guild.cpp, discord-public-user.cpp, discord-user-agent.cpp, discord-websockets.cpp, http-common.c, http-common.h, json-printf.c, json-scanf.c, json-scanf.h, ntl.h
1. refactor: replace struct json_token and struct api_resbody_s with struct sized_buffer #148 
2. refactor: rename some websockets attributes to better reflect the fact that they store timestamp data 
3. feat: add ping functionality which closes #146
=> Push changes that should improve readability and functionality

discord-public-guild.cpp, libdiscord.h
Add remove guild member functionality to guild::member.
=> Add remove guild member

test-json-scanf.c
add testing for json string unescaping
=> n1612060613

json-string.c
rename variables to improve the clarity of the code
=> n1612060846

json-scanf.c
unescape strings according to JSON RFC
=> n1612061090

json-string.c
rename variables to improve the clarity
=> n1612062197

ntl.c, ntl.h
add ntl_calloc_init/ntl_malloc_init to allow customized initialization
=> n1612121185

discord-public-channel.cpp, discord-public-guild.cpp, libdiscord.h, orka-utils.c, orka-utils.h
Changed timestamps and `orka_timestamp_ms()` to `int64_t` .
=> Changed timestamps and `orka_timestamp_ms()` to `int64_t` .

orka-utils.h
=> n1612161382

ntl.c, ntl.h, test-json-scanf-array.c
add element size and fixes ntl_dup to be consistant with strdup
=> n1612161469

bot.config
disable dump.curl which creates a huge file
=> n1612290996

README.md
add the windows subsection to make the instructions more obvious
=> n1612293112

docs/BUILDING_WITH_WINDOWS.md
When I added Windows buiding procedures, I just compiled my code and forgot to run, so it was having some errors. Now, I added some missing important instructions.
=> Add important details to Windows building

discord-public-guild.cpp
Fix simple error of ID being array
=> Fix simple error of ID being array

discord-websockets.cpp, orka-utils.h
=> Add OS detection

bot-echo.cpp, discord-common.h, discord-public.cpp, discord-websockets.cpp, libdiscord.h
Change "Message Delete" callback to specific callback type for delete
=> Change "Message Delete" callback to specific callback type for delete

docs/CODING_GUIDELINES.md
add a section about conditional compilation
=> n1612392680

discord-public.cpp
Add DM messages to intents when adding message callback
=> Add DM messages to intents when adding message callback

docs/CODING_GUIDELINES.md
add Linux kernel coding style as the fall back for subjects that are not covered in our guideline
=> n1612404703

Makefile
merge discord.mk and github.mk to Makefile
=> n1612422956

Makefile
=> n1612425697

CMakeLists.txt
=> n1612428831

json-scanf.c
=> n1612428858

bots/bot-log.cpp, discord-common.h, discord-public.cpp, discord-websockets.cpp, libdiscord.h
Add guild member callbacks and bots/bot-log.cpp to test and examplify
=> Add guild member callbacks and bots/bot-log.cpp to test and examplify

json-scanf.c
use a more descriptive field name and support %.*E %?E
=> n1612453051

bots/bot-echo.cpp, discord-common.h, discord-public.cpp, discord-websockets.cpp, libdiscord.h
Add message delete bulk callback
=> Add message delete bulk callback

CMakeLists.txt, ntl.c, ntl.h, orka-utils.c, orka-utils.h, test/test-json-scanf-array.c
add ntl_from_buf and json_array_str_to_ntl to simplify the implementation of json_list_load
=> n1612489207

orka-utils.c
json_array_str_to_ntl should only return 0 or 1
=> n1612492118

orka-utils.c, orka-utils.h, test/test-json-scanf-array.c
follow the convention to rename as orka_str_to_ntl
=> n1612498005

json-scanf.c
check the return value of function pointer, and dont count %E which is always applied
=> n1612613597

orka-utils.h, test/test-json-scanf-array.c, test/test-json-string.c
fixes a missing int64_t definition and some format string warnings
=> n1612659878

json-string.c
remove namespace in comments which cause false positive
=> n1612663813

Makefile
allow incompatible pointer usage in C
=> n1612667068

test/test-json-scanf-array.c
free all memory blocks to make detecting unfreed temp memory blocks easier
=> n1612667118

Makefile
add make targets: common, discord, github, orka
=> n1612675690

Makefile
=> n1612677482

README.md
update the build instruction by removing discord.mk
=> n1612719912

CMakeLists.txt
=> n1612773469

github-v3-git-op.cpp, github-v3.hpp, test/test-git2.cpp
upgrade to allow cross repo commit and pull
=> n1612773814

test/test-git2.cpp
use default configs if -c is not spelcified
=> n1612813326

README.md, docs/COMMIT_GUIDLINES.md
add commit guildelines to make commit easier for beginners
=> n1612817417

.gitignore
=> n1612817650

docs/COMMIT_GUIDLINES.md
add the link of getting github access token
=> n1612817883

libdiscord.h
Change `activity::dati` to use `activitity_types::code` instead of `types::code`
=> Change activity::dati to use activitity_types::code instead of types::code

docs/COMMIT_GUIDLINES.md
explain where to run test-git2.exe
=> n1612828961

discord-public-channel.cpp
Add `referenced_message` loading to `channel:message::json_load`
=> Add referenced_message loading to channel:message::json_load

docs/COMMIT_GUIDLINES.md
=> n1612832504

json-scanf.c, test/test-json-scanf-E.c
support %E without any keys; fix some bugs; add a test
=> n1612856628

json-scanf.c, json-scanf.h, test/test-json-scanf-E.c
define the function to check whether a field is defined
=> n1612871486

json-scanf.h, ntl.c, ntl.h
=> n1612872118

ntl.c
fixes a bug in ntl_calloc_init which zero initialized elements
=> n1613017760

test/test-json-load.cpp
add a test example to test json_load from json files without running a bot
=> n1613018002

discord-public-guild.cpp, libdiscord.h
Improve `guild::json_load`.
Please use `Merge Squash`.
=> Improve guild::json_load

discord-public.cpp, libdiscord.h
Add `add_intents` and use it inside `setcb`
=> Add add_intents and use it inside setcb

json-actor.c, test/test-json-actor.c
add json-actor.c for injector/extractor
=> n1613043375

json-actor.c, test/test-json-actor.c
simplify the code and add error checkings
=> n1613046465

ntl.c, ntl.h
Change `int` use to `size_t` inside `ntl.h` and `ntl.c`
Please use `Merge Squash`
Reason: https://stackoverflow.com/questions/11438794/is-the-size-of-c-int-2-bytes-or-4-bytes
Seems like the minimum size for an int in C is `16-bit`.
=> Change int use to size_t inside ntl.h and ntl.c

json-actor.c, test/test-json-actor.c
add more tagged union to improve the clarity of the basic data structures
=> n1613069664

json-actor.c
fixes the error of bounds check
=> n1613071941

json-actor.c
fixes warnings and improve the error checking message
=> n1613072962

json-actor.c, test/test-json-actor.c
adjust the pos to skip [ from copying a key
=> n1613073963

json-actor.c
=> n1613075657

json-actor.c, test/test-json-actor.c
=> n1613077174

json-actor.c
improve error handling and allow pasrsing a list of values or apath-values for testing
=> n1613084795

json-actor.c, test/test-json-actor.c
improve code clarity by rename complex-value to composite-value etc
=> n1613089250

json-actor.c, test/test-json-actor.c
prepare for json_injector implementation
=> n1613111833

json-actor.c, test/test-json-actor.c, test/test-json-injector.c
add json_injector implementation and a test
=> n1613162669

json-actor.c, test/test-json-injector.c
=> n1613164519

json-actor.c, test/test-json-injector.c
=> n1613167267

json-actor.c, test/test-json-injector.c
json_injector works for the basic bases
=> n1613185937

CMakeLists.txt
=> n1613186156

json-actor.c, test/test-json-actor.c, test/test-json-injector.c
try different delimiter for keys
=> n1613188225

json-actor.c, test/test-json-actor.c
use a more meaningful variable name
=> n1613190125

json-actor.c, test/test-json-actor.c, test/test-json-injector.c
allow using comma to seperate kv and v
=> n1613194804

json-actor.c, json-actor.h, test/test-json-actor.c, test/test-json-injector.c
allow skipping {} at the top level for object
=> n1613207771

json-actor.c, test/test-json-actor.c, test/test-json-injector.c
=> n1613208469

json-actor.c, json-actor.h, test/test-json-actor.c, test/test-json-injector.c
make the toplevel spec as the spec for injector/extractor and rename types and variables according to the change
=> n1613215669

discord-public.cpp
Remove unnecessary cast of sizeof
=> Remove unnecessary cast of sizeof

json-actor.c
improve code clarity of switch stmts by removing redundant curly brackets
=> n1613239269

json-actor.c
support | as the key delimiter
=> n1613239910

CMakeLists.txt, json-actor.c, json-actor.h, test/test-json-actor.c, test/test-json-injector.c
support configurating the injection from @ parameter
=> n1613249721

json-actor.c
=> n1613250462

CMakeLists.txt, Makefile, json-actor.c, test/test-json-injector.c
include header instead of code in a test
=> n1613264712

Makefile
=> n1613279660

Makefile
rebuild *.exe if libdiscord.a is updated
=> n1613279996

json-actor.c
support native format string action
=> n1613280203

test/test-json-actor.c, test/test-json-injector.c
test escaping and native format string
=> n1613280566

CMakeLists.txt
=> n1613283501

json-actor.c
fixes a bug that should return next_pos for NULL
=> n1613283593

github-v3-git-op.cpp
refactor git-op to use json_inject
=> n1613283985

test/test-json-injector.c
add a test to test native format string
=> n1613284068

json-actor.c, test/test-json-injector.c
free all allocated memory blocks
=> n1613291518

json-actor.c, test/test-json-injector.c
=> n1613318200

json-actor.c
the handle of double should be based on type
=> n1613319543

discord-public-guild.cpp
refactor public-guild.cpp to use json_inject
=> n1613319476

json-actor.c
use if-else for CV_OBJECT/CV_ARRAY to improve code clarity
=> n1613345324

github-v3-git-op.cpp
delete the usage of json_asprintf
=> n1613352484

json-actor.c, test/test-json-actor.c
remove one tag and use is_object to improve code clarity
=> n1613354970

json-actor.c
convert PUSH etc macros to functions to improve debuggability, rename enum type to improve code clarity, extract prepare_actor to be reused for extractor
=> n1613358399

discord-public-guild.cpp
refactor the code to use json_inject and correct the comment
=> n1613353092

json-actor.c
simplify the code to improve clarity and add # to support extracting list of tokens
=> n1613409556

test/test-json-actor.c, test/test-json-load.cpp
=> n1613409734

test/test-json-load.cpp
=> n1613410256

json-data/discord-embed.json, json-scanf.c, test/test-embed-from-json.cpp
=> n1613413869

libdiscord.h
Use code instead of int and document guild enums
=> Use code instead of int and document guild enums

docs/COMMIT_GUIDLINES.md
Add `Semantic Commit Messages` to `COMMIT_GUIDLINES.md` (credits to @LucasMull)
Note: please use `Merge Squash`.
=> Add Semantic Commit Messages to COMMIT_GUIDLINES.md (credits to @LucasMull)

docs/COMMIT_GUIDLINES.md
docs: explains when one should use "easy commit"
=> n1613440689

json-actor.c
fix: the escaped string is not null terminated, this fixes this problem
=> n1613440815

json-string.c
docs: explains why we have this continue
=> n1613440904

json-extractor.c, test/test-json-extractor.c
feat: initial implementation of json_extract
=> n1613440991

json-string.c, test/test-json-string.c
fix: the unescaping of emoji unicode
=> n1613453242

test/test-utf8.c
test: add a test to test new utf8 encoding/decoding
=> n1613453369

CMakeLists.txt
test: add more test code to cmake
=> n1613453476

json-scanf.c
fix: a logic error in the detection of empty object/array
=> n1613464700

json-extractor.c, test/test-json-extractor.c, test/test-utf8.c
feat: improve the code clarity and fix a logic bug of detecting empty object/array
=> n1613465975

json-actor.c, json-extractor.c, test/test-json-extractor.c
fix: release all memory blocks, support accessing by index, add test
=> n1613467830

json-actor.c, json-actor.h, test/test-json-extractor.c
refactor: merge json-extractor.c to json-actor.c and add more comments
=> n1613487987

json-actor.c
feat: add a rudimentary pointer check for the operands of json_inject
=> n1613507143

json-actor.c, test/test-json-actor.c
docs: explains why static is needed; refactor: move stack to its use
=> n1613509846

json-actor.c
fix: a bug of treating bool as int, it causes oob read
=> n1613514905

README.md
docs: update the discord link with server status and move the link to the top
=> n1613520873

README.md
docs: add the keywords to be more searchable
=> n1613521247

bots/bot-embed.cpp, bots/bot-embed.json, orka-utils.c
Please do NOT use `Merge Squash`.
=> Embed timestamp

orka-utils.c
fix: revert the change of encoding timestamp with double quotes
=> n1613531562

json-actor.c
feat: correctly handle nested objects/arrays and return the number of arguments that are applied
=> n1613543873

test/test-json-extractor.c
test: add tests to test extracting nested objects
=> n1613544482

json-actor.c, test/test-json-actor.c, test/test-json-extractor.c
feat: support `.` to connect multiple keys and add a test
=> n1613545687

json-actor.c
fix: a bug that does not advance key correctly, and compilation warnings
=> n1613551614

test/test-json-extractor.c
=> n1613551645

github-v3-git-op.cpp
fix: json_ainject has one less size_t pointer argument which can be misused
=> n1613577630

json-actor.c, json-actor.h, test/test-json-actor.c, test/test-json-extractor.c
refactor: make json_extract return size_t instead of int as recoverring errors will only make troubleshotting problem harder
=> n1613577768

json-actor.c
refactor: use tokens instead of t to improve the readability of the code
=> n1613578784

github-v3-git-op.cpp
refactor: use json_extract in git-op so we can test it in use
=> n1613579187

json-actor.c
feat:  a better syntax error check
=> n1613594952

json-data/eddb-api.json
test: add eddb-api openAPI spec
=> n1613609134

json-actor.c, json-actor.h
feat: add the capability to enable/disable pointer availability check
=> n1613630276

json-actor.c
fix: a bug that checks if a char is a digit
=> n1613663595

json-actor.c
=> n1613669541

json-actor.c
wip: add query injection code and fix a bug of not setting enabler
=> n1613671170

test/test-json-actor.c, test/test-json-injector.c
test: add tests for query_injection and json_injection
=> n1613671284

json-actor.c
refactor: make sure all key structs are initialized properly and rename variables to improve code clarity
=> n1613701968

json-actor.c
refactor: work around incompatible pointer warning
=> n1613751574

json-actor.c, json-printf.c, json-scanf.c, json-scanf.h, json-string.c, test/test-json-extractor.c, test/test-json-scanf-array.c, test/test-json-string.c
refactor: rename json_escape_string to json_string_escape to be consistent with url_encode/decode
=> n1613758093

json-actor.c, json-actor.h, json-string.c, test/test-json-injector.c
feat: query_inject works for a simple test
=> n1613770116

test/test-json-actor.c, test/test-json-injector.c
=> n1613770653

json-actor.c, test/test-json-injector.c
feat: generating the leading question mark if there is any query strings
=> n1613780885

CMakeLists.txt, test/test-json-load.cpp
=> n1613787996

test/test-identify.cpp
=> n1613788096

Makefile
refactor: add libdiscord target so we can just build the library
=> n1613839469

Makefile, common/curl-websocket-utils.c
feat: support builing with gcc and bearssl
=> n1613850811

Makefile
=> n1613854302

bots/bot-echo.mk
feat: add a makefile to make bot-echo
=> n1613914693

scripts/docker-install.sh
add the script to copy files into a docker container
=> n1613915797

scripts/docker-install.sh, scripts/release.sh
feat: add scripts to release as a tar ball
=> n1613916717

scripts/docker-install.sh
=> n1613935345

common/json-actor.c
wip: we need to support %S in extract
=> n1613935448

common/json-scanf.c
refactor: use VASSERT_S to print out more informative diangosis messages
=> n1613940676

Makefile, common/json-scanf.c
refactor: enable json verbose debugging from DEBUG_JSON thru make cli
=> n1613953458

github-v3-git-op.cpp
refactor: json_extract works well so we can delete json_scanf calls
=> n1613978602

common/json-actor.c, common/orka-utils.c, github-v3-git-op.cpp
feat: fix compilation warnings, use json_extract so it can be tested
=> n1613979856

bots/bot-echo.cpp
fix: add message replying to `bot-echo.cpp`
=> fix: add message replying to bot-echo.cpp

discord-public-channel.cpp, libdiscord.h
feat: add `channel::message::edit`
=> feat: add channel::message::edit

test/test-json-injector.c
refactor: @ is deprecated, and @A should be used
=> n1614015719

test/test-json-injector-1.c
test: add another test to test other combinations of k/v
=> n1614015835

common/json-actor.c, common/ntl.c, common/ntl.h
feat: improve error checks and add context to make ntl_apply and ntl_fmap more useful
=> n1614069019

common/json-actor.c
=> n1614069194

CMakeLists.txt, common/jqbs.c, test/test-jqbs.c
feat: add jqbs to generate the conversion between JSON/query/body and struct
=> n1614069339

discord-websockets.cpp, test/test-json-scanf-array.c
fix: comment out the code that is not fully checked in yet, fix a missing refactor
=> n1614087154

common/jqbs.c
=> n1614087477

common/json-actor.c
feat: support uint64_t as a builtin conversion; fix: oob reads
=> n1614120159

common/jqbs.c, test/test-jqbs.c
feat: generate more correct boilerplate code
=> n1614120807

specs/discord/template-dati.json
=> n1614120921

CMakeLists.txt
=> n1614121032

common/json-actor.c
refactor: rename the function to reflect its function
=> n1614121598

common/jqbs.c
refactor: improve the format of generated code
=> n1614122930

common/jqbs.c
fix: compilation errors of generated code
=> n1614123167

Makefile, specs/template-dati.json
fix: disable specs and it should be invoked explicitly
=> n1614150589

Makefile
=> n1614150880

.gitignore
fix: ignore generated CC files
=> n1614150930

common/jqbs.c, common/json-printf.c, test/test-jqbs.c
fix: the regression caused by refactorying
=> n1614180965

common/json-actor.c
fix: the regression and the bad use of switch
=> n1614182014

common/ntl.c
refactor: we dont intend to recover from user-defined function error, this will simplify the code a lot
=> n1614182166

github-v3-git-op.cpp
=> n1614182246

test/test-jqbs-gen.c
feat: add the main to invoke jqbs.c
=> n1614182342

CMakeLists.txt
=> n1614182622

specs/template.json
=> n1614183304

common/jqbs.c, test/test-jqbs-gen.c, test/test-jqbs.c
feat: support array/enum/comment
=> n1614193631

common/json-actor.c
feat: improve the debugging messages and fix a bug of not moving pointer correctly
=> n1614225019

common/json-struct.c, test/test-json-struct-gen.c
feat: generate the correct code that can be compiled and linked
=> n1614225129

CMakeLists.txt, test/test-json-actor.c, test/test-json-extractor.c
=> n1614225213

specs/user.json
feat: add discord::user dati spec
=> n1614225283

bots/cee/embed.json
=> n1614235836

docs/CODING_GUIDELINES.md
feat: add a link about C vs C++
=> n1614236871

common/json-struct.c, test/test-json-struct-gen.c
=> n1614261495

common/json-struct.c, test/test-json-struct-gen.c
feat: improve the usage message and support generating code without namespace
=> n1614266619

common/json-struct.c
=> n1614273157

discord-public-emoji.cpp, libdiscord.h, specs/emoji.json
feat: convert and generate discord::emoji
=> n1614275500

common/json-struct.c
=> n1614283394

bots/cee/embed.json, specs/role.json
fix: a type error in role.json and typo in status
=> n1614306638

bots/bot-create-role.cpp
fix: enable capturing the role response
=> n1614306829

common/json-actor.c, common/json-struct.c, discord-public-channel.cpp, discord-public-guild.cpp, discord-websockets.cpp, test/test-json-actor.c, test/test-json-extractor.c, test/test-json-injector-1.c, test/test-json-injector.c
refactor: rename @A as @arg_switches to improve code clarity
=> n1614312850

Makefile, libdiscord.h, specs/entry.optional_info.json, specs/template.json, test/test-json-struct-gen.c
feat: port more datis to specs and build actor-gen.exe first
=> n1614319523

.gitignore
feat: ignore generated header files
=> n1614319638

libdiscord.h, specs/webhook.json
feat: convert webhook::dati to webhook.json spec
=> n1614324961

common/json-struct.c
feat: support user-defined string to type conversion
=> n1614373641

discord-public-guild.cpp, discord-websockets.cpp, libdiscord.h, specs/guild.member.json, specs/guild.membership_screening.field.json, specs/guild.membership_screening.json, specs/guild.welcome_screen.json, specs/guild.welcome_screen.screen_channel.json, specs/invite.json, specs/invite.metadata.json, specs/user.connection.json, specs/voice.json, specs/voice.region.json
feat: convert more dati defintions to use specs
=> n1614373939

Makefile, common/json-struct.c, specs/emoji.json, specs/entry.optional_info.json, specs/guild.member.json, specs/invite.json, specs/invite.metadata.json, specs/role.json, specs/role_tags.json, specs/template.json, specs/user.connection.json, specs/user.json, specs/voice.json, specs/webhook.json, test/test-json-struct.c
feat: fix memory allocation in code gen
=> n1614404130

common/json-actor.c
fix: suppress the debugging info by default
=> n1614444929

common/json-actor.c, common/json-struct.c, test/test-json-extractor.c, test/test-json-injector.c, test/test-json-struct.c
=> n1614478868

common/ntl.c, common/ntl.h
=> n1614478957

Makefile
=> n1614479021

libdiscord.h, specs/channel.overwrite.json
feat: convert overwrite::dati to be generated by a spec
=> n1614535496

specs/wip/guild.channel.json
=> n1614535599

common/json-actor.c
feat:support converting string to hex 64-bit int
=> n1614540784

common/json-actor.c
fix: accept s_as_hex64 and the correct base
=> n1614541550

discord-public-user.cpp, docs/DISCORD_ROADMAP.md, libdiscord.h
=> add: user::me::leave_guild

common/json-actor.c
feat: support detecting the existence of a key
=> n1614570592

common/json-struct.c, test/test-json-extractor.c, test/test-json-struct.c
feat: suppor the default injection settings
=> n1614573376

common/json-struct.c
=> n1614573788

common/json-struct.c
refactor: improve code clarity
=> n1614575060

libdiscord.h, specs/guild.channel.json
feat: support create_build_channel
=> n1614580399

specs/guild.enum.json
convert guild enums to be generated by a spec
=> n1614585062

discord-public-guild.cpp, libdiscord.h, specs/guild.create-channel.json
feat: hook up generated create_channel::params
=> n1614620171

common/json-struct.c
feat: dont check null if it is an array
=> n1614630847

discord-public-emoji.cpp
=> n1614716832

test/test-git2.cpp
=> n1614716896

discord-common.h, discord-public-channel.cpp, discord-public-guild.cpp, discord-public-user.cpp, libdiscord.h, specs/guild.enum.json, specs/guild.json
feat: convert guild::dati to be generated by specs
=> n1614732366

discord-public-guild.cpp, libdiscord.h, specs/guild.create_role.json
feat: create role params is generated by a spec
=> n1614734188

common/json-actor-boxed.c, common/json-actor-boxed.h, common/specs.h, libdiscord.h, specs/channel.allowed_mentions.json, specs/channel.attachment.json, specs/channel.followed_channel.json, specs/channel.mention.json
feat: convert more dati to be generated by specs
=> n1614745014

common/json-struct.c
=> n1614745123

discord-common.h, discord-public-channel.cpp, libdiscord.h, specs/channel.message.json, specs/channel.types.json
feat: convert all message::dati's dependency to be generated by specs
=> n1614765986

common/json-struct.c, discord-public-channel.cpp, discord-websockets.cpp, libdiscord.h, specs/channel.message.json, specs/channel.reaction.json, specs/emoji.json, specs/guild.create-channel.json, specs/guild.membership_screening.json, specs/guild.welcome_screen.json, specs/invite.json, specs/role.json, specs/template.json, specs/voice.json, specs/webhook.json, test/test-spec.c
feat: migrate message::dati to be generated by specs
=> n1614790890

libdiscord.h, specs/role.json, specs/voice.json, specs/webhook.json
refactor: use explicit namespace so we can include files directly
=> n1614794464

test/test-json-struct-gen.c
feat: enable source spec location
=> n1614803301

common/json-actor.c, common/json-actor.h, common/json-struct.c, libdiscord.h, specs/guild.modify_member.json
feat: add the source spec location to generated code; add modify_member::params
=> n1614803258

test/test-json-struct.c
test: update the test to include source location
=> n1614803425

specs/guild.modify_member.json
=> n1614818461

common/json-struct.c
feat: improve the debuggablity of spec
=> n1614819118

common/json-struct.c
=> n1614884196

common/ntl.c, common/ntl.h, test/test-ntl.c
feat: add comments and use typedef ntl_t to improve code clarity
=> n1614884257

test/test-json-struct.c
=> n1614884572

common/ntl.c, common/ntl.h
feat: support using ntl.c as included file
=> n1614886999

common/json-struct.c
feat: support option and nullable
=> n1614926640

common/json-actor.c, common/json-actor.h, common/json-struct.c, discord-public-channel.cpp, specs/channel.objects.json
feat: support dynamic type and disable overwrite::from/to_json
=> n1614965298

common/json-actor.c, common/json-struct.c
feat: add more source locations to make debug easier
=> n1615008017

common/json-struct.c, test/test-json-struct-gen.c, test/test-spec.c
feat: support generating C code
=> n1615091918

Makefile, common/json-struct.c, test/test-json-struct-gen.c
feat: improve code clarity with ntl_t and generate C code but do not compile them yet
=> n1615128968

Makefile
fix: Makefile to install generated header files
=> n1615138404

README.md
=> n1615156057

common/json-struct.c, libdiscord.h, specs/channel.bulk-delete-messages.json, specs/channel.create-channel-invite.json, specs/channel.edit-channel-permissions.json, specs/channel.follow-news-channel.json, specs/channel.get-reactions.json, specs/channel.group-dm-add-recipient.json, specs/channel.modify-channel.json, specs/emoji.create-guild-emoji.json, specs/emoji.modify-guild-emoji.json
=> n1615180169

libdiscord.h, specs/template.create-guild-from-template.json, specs/template.create-guild-template.json, specs/template.modify-guild-template.json
feat: support more endpoints params
=> n1615183692

libdiscord.h, specs/user.create-group-dm.json, specs/user.modify-curent-user.json, specs/webhook.create-webhook.json, specs/webhook.edit-webhook-message.json, specs/webhook.execute-webhook.json, specs/webhook.modify-webhook.json
feat: support more endpoints params
=> n1615206262

libdiscord.h, specs/guild.create-guild.json
feat: add create_guild::params spec
=> n1615233046

discord-common.h, libdiscord.h, specs/audit_log.json
feat: convert audit_log::dait to be generated by a spec
=> n1615237391

common/json-actor.c, common/json-actor.h, common/json-struct.c, test/test-json-struct-gen.c
feat: support generating all structs and all enums in seperated files
=> n1615273914

Makefile, discord-common.h, libdiscord.h
feat: replace structs, enums, and forward declarations with generated headers
=> n1615274123

specs/gateway.json
feat: add gateway specs, but it is not used yet
=> n1615322166

common/json-actor.c, common/json-struct.c
=> n1615322123

Makefile
feat: if any spec is changed, we rebuilt all headers
=> n1615322206

bots/bot-elitebgs.cpp, common/json-struct.c, common/user-agent.c, common/user-agent.h, discord-public-channel.cpp, discord-public-emoji.cpp, discord-public-guild.cpp, discord-public-user.cpp, discord-websockets.cpp
=> n1615436678

CMakeLists.txt, Makefile, jsB/jsB-discord-client.cpp, jsB/jsB.h, mujs/jsrun.c, mujs/mujs.h
feat: add the first mujs binding
=> n1615485324

Makefile
feat: force the sequential order of bot
=> n1615653279

discord-user-defined.cpp, libdiscord.h, user-defined.h
fix: a change overwritten by my previous change, add user-defined functions that cannot be mapped back to API docs
=> n1615949274

discord-public-channel.cpp
fix: a regression caused by chaning the immediate parent namespace
=> n1615951753

discord-user-defined.cpp
feat: delete one or more messages of an author
=> n1615961041

discord-public-channel.cpp, libdiscord.h
feat: add channel::delete_message
=> n1615961004

discord-public-guild.cpp
=> n1616009414

common/orka-utils.c
fix: add thread safe macro before including time.h
=> fix: add thread safe macro before including time.h

docs/BUILDING_WITH_WINDOWS.md
fix: update windows build tutorial
=> fix: update windows build tutorial

docs/BUILDING_WITH_WINDOWS.md
fix: small fix at windows build tutorial
=> fix: small fix at windows build tutorial

specs-code/voice.c, specs-code/voice.h, specs/voice.json
refactor: rename discord_voice to discord_voice_state
=> refactor: rename discord_voice to discord_voice_state

docs/BUILDING_WITH_WINDOWS.md
fix: update Windows build tutorial to C migration
=> fix: update Windows build tutorial to C migration

common/json-actor.c, common/json-struct.c, test/test-git2.c
=> n1616706453

docs/BUILDING_WITH_WINDOWS.md
=> fix: windows build tutorial

.vscode/c_cpp_properties.json
fix: remove intelliSenseMode as it causes problems in 64-bit machines
=> fix: remove intelliSenseMode as it causes problems in 64-bit machines

CMakeLists.txt
refactor: dont rebuild sqlite3
=> n1617257227

common/ntl.c, common/ntl.h, discord-channel.c
fix: add ntl_length_max and bulk delete count verification
=> fix: add ntl_length_max and bulk delete count verification

discord-channel.c, discord-misc.c
fix: add timestamp verification to bulk_delete and delete_by_author
=> fix: add timestamp verification to bulk_delete and delete_by_author

common/json-actor.h, common/json-parser.c
=> feat: json_strdup

docs/DISCORD_ROADMAP.md
docs: mark bulk delete checkbox
=> docs: mark bulk delete checkbox

discord-gateway.c
feat: update gateway version to v8
=> feat: update gateway version to v8

discord-voice-connections.c, discord-voice-connections.h
=> fix: discord_send_speaking

discord-voice-connections.c
fix: use vc->udp_service.ssrc instead of vc->ssrc
=> fix: use vc->udp_service.ssrc instead of vc->ssrc

docs/PROJECT_OUTLINE.md
I have created a "project outline" for new-comers and skilled developers to read to get a run down of where Orca's important parts are, as well as what each piece is for.
=> Added PROJECT_OUTLINE.md

github-adapter.c, github-client.c, github-internal.h, github.h, test/test-git2.c
refactor(github): keep github code consistent to the other wrapped APIs
=> n1628292834

discord-guild.c, discord.h, docs/DISCORD_ROADMAP.md
Wrapping another endpoint
Sorry I realised I accidentally messed up sth in git in the previous pr
=> feat: added delete_guild_integrations

specs/discord/user.json
Added the new "banner" field into the user structure.
=> feat(discord): add banner field to 'struct discord_user'

discord-guild-template.c, discord.h, examples/bot-guild-template.c
I have implemented and documented a new endpoint for syncing the state of a guild template.
=> feat: added discord-sync-guild-template

discord-client.c, discord.h, examples/bot-slash-commands.c, examples/bot-slash-commands2.c, specs-code/discord/application_commands.c, specs-code/discord/application_commands.h, specs-code/discord/one-specs.h, specs/discord/application_commands.json
I have added a convenience function for assigning a command to 'aliases,' or put simpler, assigning the same callback to multiple commands in a single function call.
=> feat: added discord_set_on_commands
